name: nps s390x

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]
    branches: [ master ]  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: chmod +x build.assets.sh && ./build.assets.sh

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: nps_s390x
        path: ${{ github.workspace }}/nps_s390x

